.PHONY: install-dependencies
install-dependencies:
	luarocks install --local lua-cjson
	luarocks install --local luasec
	luarocks install --local luasocket
	luarocks install --local md5
	luarocks install --local xml
	luarocks install --local lua-requests

